URL = "http://91.210.171.73:8080"
USER_PATH = "/api/token/auth/"
ALL_ANIMALS_CATEGORY = "/api/category/"
CATEGORY_BY_PARAMETER = "/api/category/{id}/"
ALL_PETS = "/api/pet/"
PETS_BY_PARAMETER = "/api/pet/{id}/"
