URL = "http://127.0.0.1:8080/api/docs/"
USER_PATH = "/api/token/auth/"
ALL_ANIMALS_CATEGORY = "/api/category/"
CATEGORY_BY_PARAMETER = "/api/category/{id}/"
ALL_PETS = "/api/pet/"
PETS_BY_PARAMETER = "/api/pet/{id}/"
